---
- hosts: localhost
  connection: local
  vars:
    base_image: fedora:27
    image_name: hipchat
    container_engine: buildah
    dockerhub_user: mklvr
  tasks:
  - name: Obtain base image and create a container out of it
    command: 'buildah from --name {{ image_name }} docker://{{ base_image }}'
    become: true
    when: container_engine == 'buildah'

  - name: Add the newly created container to the inventory
    add_host:
      hostname: '{{ image_name }}'
      ansible_connection: '{{ container_engine }}'
      ansible_python_interpreter: /usr/bin/python3

  - name: Run the role in the container
    delegate_to: '{{ image_name }}'
    include_role:
      name: hipchat

  - block:
    - name: Configure the container
      shell: |
        export run_command='docker run -v /tmp/.X11-unix:/tmp/.X11-unix -v ${HOME}/Downloads:/home/user/Downloads:z -v ${HOME}/.config/Atlassian:/home/user/.config/Atlassian:Z -e DISPLAY=unix${DISPLAY} --rm --user 1000 --device /dev/snd  --device /dev/dri/card0 --name {{ image_name }} {{ dockerhub_user }}/{{ image_name }} hipchat4'
        
        buildah config --author="Mike Oliver <mike@mklvr.io>" --user="1000:1000" {{ image_name }}
        buildah config --label RUN="$run_command" {{ image_name }}

    - name: Commit the container and make it an image
      command: 'buildah commit --rm {{ image_name }} docker-daemon:{{ dockerhub_user }}/{{ image_name }}:latest'
    when: container_engine == 'buildah'

