---
- hosts: localhost
  remote_user: root
  become: yes
  tasks:
    - name: Add packages to fetch hipchat repo
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: latest
      with_items:
        - lsb-release
        - wget
        - apt-transport-https
    - name: Import hipchat key
      shell: bash -c "wget -O - https://atlassian.artifactoryonline.com/atlassian/api/gpg/key/public | apt-key add -"
    - name: Adding hipchat repository
      apt_repository:
        repo: deb https://atlassian.artifactoryonline.com/atlassian/hipchat-apt-client {{ ansible_lsb.codename }} main
        state: present
    - name: Add hipchat
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: latest
      with_items:
        - hipchat4
        - libqt5gui5
    - name: Adding user to run application
      user:
        name: user
        shell: /bin/bash
        state: present
        uid: 1000
